In [2]:
import numpy as np

## Practical Examples

In [25]:
#Create a list of numbers

nyc_temp = [39, 42, 50, 62, 72, 80, 85, 84, 76, 65, 54, 44]
type(nyc_temp)

list

In [26]:
#Turn a list into a numpy array

nyc_temp_np = np.array(nyc_temp)
nyc_temp_np

array([39, 42, 50, 62, 72, 80, 85, 84, 76, 65, 54, 44])

In [27]:
# Convert to celsius 

nyc_temp_celsius = (nyc_temp_np - 32) * (5/9)
nyc_temp_celsius

array([ 3.88888889,  5.55555556, 10.        , 16.66666667, 22.22222222,
       26.66666667, 29.44444444, 28.88888889, 24.44444444, 18.33333333,
       12.22222222,  6.66666667])

In [19]:
#Multiply numpy arrays (calculating square footage)

lengths_of_each_room = np.array([10, 12, 20, 5])
widths_of_each_room = np.array([13, 15, 16, 4])
areas_of_each_room = lengths_of_each_room * widths_of_each_room

print ('Here is an array with the square footages for each room:', areas_of_each_room)

Here is an array with the square footages for each room: [130 180 320  20]


## Basic Calculations

In [31]:
arr = np.array([1,2,3])

In [32]:
#Addition

np.add(arr,1)

array([2, 3, 4])

In [33]:
#Subtraction

np.subtract(arr,2)

array([-1,  0,  1])

In [34]:
#Multiplication

np.multiply(arr,3)

array([3, 6, 9])

In [36]:
#Division

np.divide(arr,4)

array([0.25, 0.5 , 0.75])

In [37]:
#Power 

np.power(arr,5)

array([  1,  32, 243])

In [49]:
#Sine of an array

np.sin(arr)

array([0.84147098, 0.90929743, 0.14112001])

In [50]:
#Log of an array

np.log(arr)

array([0.        , 0.69314718, 1.09861229])

In [51]:
#Absolute value of an array

np.abs(arr)

array([1, 2, 3])

In [52]:
#Round up to the nearest integer

arr_decimal = np.array([1.2,4.9,7.8])

np.ceil(arr_decimal)

array([2., 5., 8.])

In [53]:
#Round down to the nearest integer 

np.floor(arr_decimal)

array([1., 4., 7.])

In [54]:
#Round to the nearest integer

np.round(arr_decimal)

array([1., 5., 8.])

In [57]:
#Create an array: 5 elements, ranging from 0 to 4

np.full(5, range(5)) 

array([0, 1, 2, 3, 4])

## Calculating Multiple Arrays

In [40]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

In [41]:
#Add 2 arrays

np.add(arr1,arr2)

array([5, 7, 9])

In [43]:
#Subtract 2 arrays

np.subtract(arr1,arr2)

array([-3, -3, -3])

In [44]:
#Multiply 2 arrays

np.multiply(arr1,arr2)

array([ 4, 10, 18])

In [45]:
#Divide 2 arrays

np.divide(arr1,arr2)

array([0.25, 0.4 , 0.5 ])

In [46]:
#Power of 2 arrays

np.power(arr1,arr2)

array([  1,  32, 729])

In [47]:
#Are these arrays equal?

np.array_equal(arr1,arr2)

False

## Numpy Shapes

In [ ]:
#Shape is columns by row 

In [55]:
y = np.array([[1, 2, 3],[4, 5, 6]])
y.shape

(2, 3)

In [58]:
z = np.array([[[1, 2],[3, 4],[5, 6]],
             [[1, 2],[3, 4],[5, 6]]
             ])
z.shape

(2, 3, 2)

In [59]:
#Take the first row

z[0]

array([[1, 2],
       [3, 4],
       [5, 6]])